### ISSUE TITLE
Synchronizing PHP version with the minimum version required by MediaWiki used in the preview

### ISSUE THREAD

**Issue by alistair3149** [jdlrobson/skins.wmflabs.org#14]
I understand that this is a tricky situation because of WMF being on PHP 7.2 in production despite it has been dropped since MW 1.35 ([T271736](https://phabricator.wikimedia.org/T271736)). However, since the target audience of the site aren't going to hack their MW installation to use an unsupported PHP version, I think it is fair to update the PHP version according to the MW version. It is possible that some skins use newer syntax unsupported by 7.2 (e.g. Citizen currently).

**Comment by jdlrobson** [comment]
I'm using Cloud VPS so presumably I need to move off the deprecated image to upgrade

**Comment by jdlrobson** [comment]
It seems even the latest cloud vps machines require 7.2.31 :(

**Comment by alistair3149** [comment]
What a bummer :( I'm sure that it'll be updated sooner or later when PHP 7.2 is fully deprecated in WMF wikis. Until then it's probably stalled by upstream.

**Comment by jdlrobson** [comment]
I've upgraded the VPS machine today. Let me know if there are any outstanding problems. https://skins-demo.wmflabs.org/wiki/Main_Page

Unfortunately I can't preview Citizen skin because of https://github.com/StarCitizenTools/mediawiki-skins-Citizen/issues/546 but I'll track that and enable it as soon as possible!

**Comment by alistair3149** [comment]
Thanks a lot for taking the time on the side to update it!
I am just waiting for 1.39 to release this month to merge the current development branch into the main branch. I have been catching up with the skin architecture in the recent weeks and it will be a great help when it can be previewed on skin-demo! I will comment here again when the branch is merged.

**Comment by alistair3149** [comment]
The 1.39 branch is now merged into main. Would you mind to update the Citizen skin used on SkinDemo?

**Comment by jdlrobson** [comment]
Done!
