### ISSUE TITLE
Skin demo wiki is unable to load wiki page from English Wikipedia

### ISSUE THREAD

**Issue by alistair3149** [jdlrobson/skins.wmflabs.org#18]
**Describe the bug**
Skin demo wiki is unable to load wiki page from English Wikipedia.

Error message:
```ContentProvider failed to load page https://en.wikipedia.org/w/api.php?formatversion=2&format=json&action=parse&prop=revid|text|modules|sections|properties|langlinks&page=MediaWiki&skin=apioutput with following error: http-curl-error (Could not resolve host: en.wikipedia.org), http-bad-status (0 Error)```

**To Reproduce**
1. Open any page on skin demo wiki

**Expected behavior**
Skin demo wiki should load content from English Wikipedia

**Screenshots**
![image](https://user-images.githubusercontent.com/9260542/211234386-194f69f6-38f2-427a-bcbd-c0a5193ba4e9.png)

**Comment by jdlrobson** [comment]
Looks like a CURL certificate issue.

It looks like the instance is having bigger issues today possibly relating to the Cloud VPS migration. Hopefully we can get this back online.

**Comment by jdlrobson** [comment]
Okay should be fixed now! I added the following to LocalSettings.php

```

$ch = curl_init();

 $certificate = "/srv/mediawiki-vagrant/mediawiki/cacert.pem";
 curl_setopt($ch, CURLOPT_CAINFO, $certificate);
 curl_setopt($ch, CURLOPT_CAPATH, $certificate);
```
