### ISSUE TITLE
Previews while exploring skins contain errors and/or are broken

### ISSUE THREAD

**Issue by bertvandepoel** [jdlrobson/skins.wmflabs.org#21]
**Describe the bug**
When visiting all working skins, an error is being shown:
`ContentProvider failed to load page https://en.wikipedia.org/w/api.php?formatversion=2&format=json&action=parse&prop=revid|text|modules|sections|properties|langlinks&page=MediaWiki&skin=apioutput with following error: http-curl-error (Could not resolve host: en.wikipedia.org), http-bad-status (0 Error)`
This sounds like #20 has resurfaced. 

Furthermore some skins like Vector also seem to be missing CSS. 

**To Reproduce**
Curl error:
https://skins.wmcloud.org/#/skin/twentytwentyone
https://skins.wmcloud.org/#/skin/pure
https://skins.wmcloud.org/#/skin/dgraph
https://skins.wmcloud.org/#/skin/mediawikibootstrap5
https://skins.wmcloud.org/#/skin/modern

Missing CSS:
https://skins.wmcloud.org/#/skin/mirage
https://skins.wmcloud.org/#/skin/vector-2022
https://skins.wmcloud.org/#/skin/hassomecolours

**Expected behavior**
Previews showing content instead of an error and no CSS being missing

**Comment by jdlrobson** [comment]
Hey @bertvandepoel  thanks for the report. I ssh'ed in and it had run out of disk space. Could you check if this is working again now?

**Comment by bertvandepoel** [comment]
I'm glad I was able to reach you! I tried IRC, email and Twitter before I found out about this repo, but those maybe ended up getting lost in between other stuff.

It seems most skins are working again but some others are having issues, e.g. https://skins-demo.wmflabs.org//wiki/MediaWiki?useformat=desktop&uselang=en&useskin=vector-2022 , https://skins.wmcloud.org/#/skin/mirage and https://skins-demo.wmflabs.org//wiki/MediaWiki?useformat=desktop&uselang=en&useskin=pure (that last one might just be a maintenance issue on the skin side though). I'm guessing that the Curl error was fixed but other issues remain.

**Comment by jdlrobson** [comment]
It's a new MediaWiki release so some skins are going to be broken now I've upgraded. I fixe the first two and sent a pull request for the third. https://github.com/drriguz/Pure/pull/4 Let me know if you see any other broken skins! Thanks!

**Comment by bertvandepoel** [comment]
Awesome. I'll check tomorrow probably, then get back to you. It's crazy late here!

**Comment by alistair3149** [comment]
It seems that the preview for [Citizen](https://skins.wmcloud.org/#/skin/citizen) is broken as well. Is there any error log that is actionable to be fixed on the skin side?

**Comment by jdlrobson** [comment]
@alistair3149 it looks like I've just run out of disk space on the machine for new skins. Citizen seems to be working with the latest MediaWiki and is now there.

I also reviewed the API response at https://skins-demo.wmflabs.org/w/rest.php/v1/skins and disabled any broken skins (load-error tag). All previews should now be working now. Let me know if not.
