### ISSUE TITLE
#22 | Please update Lakeus skin for live preview option

### ISSUE THREAD

**Issue by winstonsung** [jdlrobson/skins.wmflabs.org#22]
**Description**
The Lakeus skin in Wikimedia Skins Lab is outdated and producing ResourceLoaderSkinModule error.

**To Reproduce**
1. Go to https://skins.wmcloud.org/#/skin/lakeus
2. Click on 'Click to preview' https://skins-demo.wmflabs.org//wiki/MediaWiki?useformat=desktop&uselang=en&useskin=lakeus
3. See error

**Expected behavior**
Should use up-to-date latest https://github.com/lakejason0/mediawiki-skins-Lakeus.git .

**Additional context**
```
Replaced deprecated PHP class alias ResourceLoaderSkinModule
with namespaced MediaWiki\ResourceLoader\SkinModule .

The class was namespaced in MediaWiki 1.39
(commit 3e2653f83bc096889d8b69d1e01a52d7de42b247,
Change-Id Id08a220e1d6085e2b33f3f6c9d0e3935a4204659),

and the deprecated class alias was removed in MediaWiki 1.42
(commit 21d8d9863b393e0bea608ac2f926b40bfecff9ad,
Change-Id I5929a2f760c8d21c1cb2542a19220a91ac7240e4).

Bug: https://github.com/lakejason0/mediawiki-skins-Lakeus/pull/38
Change-Id: I49315facdd5cc0f56485c830c020853763bf76c0
```

**Comment by winstonsung** [comment]
@jdlrobson

**Comment by jdlrobson** [comment]
Hey @winstonsung just wanted to acknowledge i've seen the request, I just haven't got round to updating Skins to the new version of MediaWiki (I'll need to dedicate half a day to do this and will do all the skins together!)

**Comment by winstonsung** [comment]
Thanks for the reply.

(just want to make sure it's not being missed. Apologize if bothered.)

**Comment by jdlrobson** [comment]
Sorry for the delay here. Migrating this is taking much longer than I expected so I've gone ahead and updated Lakeus in the mean time.
