### ISSUE TITLE
Skin Create failed

### ISSUE THREAD

**Issue by nasirkhan** [jdlrobson/skins.wmflabs.org#4]
**Describe the bug**
I created and downloaded a skin from skins.wmflabs.org but it looks different than it shows in the preview window. 

**To Reproduce**
1. Go to https://skins.wmflabs.org/#/add
2. Set a name and download it
3. Enable the skin

**Results**
* It looks like the top left menu and search box is not in right position. Also the Wikiname/ logo is not visible. On the https://skins.wmflabs.org/#/add page i saw Skinomatic 4000. 
* Also the top right links does not work

**Screenshot**
![Screenshot_2021-01-13 mediawiki136](https://user-images.githubusercontent.com/396987/104355087-5ce36980-5534-11eb-80fa-7bb643c7de3c.png)

**Comment by jdlrobson** [comment]
Can you share the zip file it generated  ?

**Comment by jdlrobson** [comment]
I had a play around with different config, and I think I've worked out what was happening.

I'm pretty sure these 2 patches will fix that. If you reload the skins.wmflabs.org tool and try saving as zip those 2 issues should be fixed now. Can you confirm?

**Comment by nasirkhan** [comment]
thanks the logo issue has been fixed. But the top right links still not working.

**Comment by jdlrobson** [comment]
That's my mistake. Reapplied the patch above and have deployed.
