### ISSUE TITLE
Please update Citizen skin for live preview option

### ISSUE THREAD

**Issue by alistair3149** [jdlrobson/skins.wmflabs.org#5]
I am the author of the Citizen skin. Would you mind to update the Citizen skin used for live preview? It is a few versions behind and I am not sure if this is the right place to request for an update. May I also ask what is the usual update procedure for the live preview?

**What is the link to the MediaWiki page of your skin?**
https://www.mediawiki.org/wiki/Skin:Citizen

**Does the skin work in 1.36?**
Yes

**Does your skin require composer or other extensions?**
No

**Does your skin have a screenshot at the path `screenshots/1280x800.png?```
Sort of, it has a light/dark suffix to it. A better screenshot is available in the infobox on the MediaWiki page

**Does your skin using PHP hooks?**
Yes

**Additional context**
None

**Comment by jdlrobson** [comment]
Sorry for the long delay here. I've had some other things to attend to, but the skin should be updated now.
https://skins.wmflabs.org/#/skin/citizen

The live preview currently involves me installing the skin on a Vagrant instance so it's currently a manual step, to make sure I get a chance to review the code I'm pulling. It also requires me updating manually, which I'm trying to get in a habit of doing more often e.g. every month.

I'm trying to move as much of the update process as possible on the wiki for instance https://www.mediawiki.org/w/index.php?title=Skin%3ACitizen&type=revision&diff=4728650&oldid=4718358 to try to get better at communicating changes that might break skins in future versions.

Thanks for your patience with me as I try to work through this process!

**Comment by alistair3149** [comment]
> Sorry for the long delay here. I've had some other things to attend to, but the skin should be updated now.
> https://skins.wmflabs.org/#/skin/citizen
> 
> The live preview currently involves me installing the skin on a Vagrant instance so it's currently a manual step, to make sure I get a chance to review the code I'm pulling. It also requires me updating manually, which I'm trying to get in a habit of doing more often e.g. every month.
> 
> I'm trying to move as much of the update process as possible on the wiki for instance https://www.mediawiki.org/w/index.php?title=Skin%3ACitizen&type=revision&diff=4728650&oldid=4718358 to try to get better at communicating changes that might break skins in future versions.
> 
> Thanks for your patience with me as I try to work through this process!

Thanks for the update! The Skins Lab has been an awesome addition and it surely benefits a lot of wiki admins to find the skin that they wanted. I'm not sure if it'll help but I noticed that there is a [very similar wiki ](https://skins.toolforge.org/wiki/Main_Page) maintained by MacFan400 that also showcases different MediaWiki skins. Maybe it can be an opportunity to join the effort?

As for the breaking changes, it is a weird process for us since our main production wiki is on LTS, so it makes development more difficult as the skin have to maintain LTS compatibility (in this case 1.35) while being able to work on latest stable as there are other wikis that also uses the skin. Unfortunately there are a lot of big (but awesome) changes on the skin architecture in recent versions so it can be daunting to track those changes and polyfill for them.

I do wish that there is a centralized place to communicate changes in skin architecture, I track the workboard on Phabriator and also the commit history of Vector closely but it can be time-consuming and difficult for a lot of skin authors.

Keep up the good work :)

**Comment by jdlrobson** [comment]
> Thanks for the update! The Skins Lab has been an awesome addition and it surely benefits a lot of wiki admins to find the skin that they wanted. I'm not sure if it'll help but I noticed that there is a very similar wiki maintained by MacFan400 that also showcases different MediaWiki skins. Maybe it can be an opportunity to join the effort?

Yep I'm aware of the MacFan400 wiki and that's another thing on my list of todos. The skins lab can be pointed at any wiki so it was on my todo to work out if our goals were similar

> I do wish that there is a centralized place to communicate changes in skin architecture, I track the workboard on Phabriator and also the commit history of Vector closely but it can be time-consuming and difficult for a lot of skin authors.

Agreed.. I am trying to help lessen the burden on skin developers by letting them know when stuff breaks. If you follow along on https://phabricator.wikimedia.org/project/view/4795/ you can get a sense of what's upcoming and planned and please do feel free to join any conversations if interested.
