### ISSUE TITLE
Please enable Evelution for live preview option

### ISSUE THREAD

**Issue by HM100** [jdlrobson/skins.wmflabs.org#8]
I'm the developer of the newly established Evelution Skin which can be found [here](https://github.com/AWikia/SkinEvelution). It is currently at version 2.3.0. Since this skin works for MediaWiki 1.36, can live preview be enabled for this skin (Evelution)?

**Comment by HM100** [comment]
It is currently in version 3.6.0 and has been evolved a lot since the issue's creation, if you want to know.

**Comment by jdlrobson** [comment]
Done! Apologies for the delay on this one!
https://skins.wmflabs.org/#/skin/evelution

**Comment by HM100** [comment]
Evelution seems to be out of sync. Skins lab has version 7 but currently, version 13 is offered as the latest version for download <https://github.com/AWikia/SkinEvelution>

**Comment by HM100** [comment]
Note: It can also be bumped to <https://github.com/AWikia/SkinEvelution/commit/fea4c8615b2fa6ef062bd0d8a09edaa9f7c0e2af> as I managed to squash the three remaining issues. It can be done at anytime.

**Comment by HM100** [comment]
Can be bumped to https://github.com/AWikia/SkinEvelution/commit/5819353c7e01ce56464d1438a400d63f5d7522fe as it evolved a lot
